- name: Add fish repository
  apt_repository:
    repo: ppa:fish-shell/release-3

- name: Install Fish
  become: true
  apt:
    name: fish
    update_cache: true

- name: Change shell to Fish
  become: true
  shell: chsh -s $(which fish)

- name: Copying starship theme to file
  shell: curl -o starship.sh https://starship.rs/install.sh

- name: Execute and accept starship theme file
  script: ./starship.sh -y

- name: Remove starship file
  file:
    state: absent
    path: ./starship.sh
