- hosts: localhost
  connection: local
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    personal: "{{ lookup('env', 'HOME') }}/personal"

  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present

  roles:
    - { role: core, tags: core }
    - { role: neovim, tags: neovim }
    - { role: fish, tags: fish }
    - { role: stow, tags: stow }
    - { role: asdf, tags: asdf }
    - { role: docker, tags: docker }
    - { role: snaps, tags: snaps }
    - { role: vscode, tags: vscode }
    - { role: slack, tags: slack }
    - { role: ssh, tags: ssh }

