- hosts: localhost
  connection: local
  become: true
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    personal: "{{ lookup('env', 'HOME') }}/personal"
    asdf_version: v0.8.1
    asdf_user: "{{ansible_user_id}}"

  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - include: tasks/core-setup.yml
    - include: tasks/fish.yml
    - include: tasks/asdf.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/ssh.yml
    - include: tasks/vscode.yml
    - include: tasks/docker.yml
    - include: tasks/slack-setup.yml
    - include: tasks/snaps.yml

  roles:
    - role: cimon-io.asdf
      asdf_plugins:
        - name: "nodejs"
          versions: ["lts", "17.2.0"]
          global: "lts"
        - name: "ruby"
          versions: ["2.5.1", "3.0.2"]
