- hosts: localhost
  connection: local
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    personal: "{{ lookup('env', 'HOME') }}/personal"
    asdf_version: v0.8.1
    asdf_user: "{{ ansible_user_id }}"

  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present

  roles:
    - { role: stow, tags: stow }
    - { role: core, tags: core }
    - { role: ssh, tags: ssh }
    - { role: neovim, tags: neovim }
    - { role: fish, tags: fish }
    - { role: asdf, tags: asdf }
    - { role: docker, tags: docker }
    - { role: snaps, tags: snaps }
    - { role: vscode, tags: vscode }
    - { role: slack, tags: slack }
    - role: cimon-io.asdf
      asdf_plugins:
        - name: "nodejs"
          versions: ["lts", "17.2.0"]
          global: "lts"
        - name: "ruby"
          versions: ["2.5.1", "3.0.2"]

