- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  become: true
  apt:
    name: ["lua5.1", "unzip", "libtool", "libtool-bin", "gettext"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 (htop, curl, wget, tilix, snapd, fira-code, snap, flameshot)
  apt:
    name: ["htop", "curl", "wget", "tilix", "snapd", "fonts-firacode", "snapd", "flameshot"]
  tags:
    - install
    - core
    - fish
    - starship

- name: Install Docker Dependencies
  apt: name={{ item }} state=latest update_cache=yes
  loop:
    [
      "apt-transport-https",
      "ca-certificates",
      "curl",
      "software-properties-common",
      "python3-pip",
      "virtualenv",
      "python3-setuptools",
    ]
  tags:
    - install
    - docker
    - core

- name: Install asdf dependencies
  apt:
    name: ["unzip", "git", "autoconf", "automake", "gcc",
  "g++", "make", "patch", "pkg-config", "binutils", "libtool", "bison", "libreadline-dev"]
  tags:
    - install
    - core
    - asdf

- name: Install node dependencies
  apt:
    name: ["gpg", "dirmngr"]
  tags:
    - install
    - core
    - asdf

- name: Install ruby dependencies
  apt:
    name: ["libssl-dev", "libyaml-dev", "zlib1g-dev", "libncurses5-dev", "libffi-dev"]
  tags:
    - install
    - core
    - asdf