- name: Install aptitude using apt
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
  tags:
    - install
    - docker

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - install
    - docker

- name: Add Docker Repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker-ce
  tags:
    - install
    - docker

- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest
  tags:
    - install
    - docker

- name: Install Docker
  become: true
  apt:
    name: docker-ce
  tags:
    - install
    - docker

- name: Adding existing user to group Docker
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  tags:
    - install
    - docker

- name: Install Docker-Compose
  become: true
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-Linux-x86_64"
    dest: "/usr/local/bin/docker-compose"
    mode: 755
  tags:
    - install
    - docker
