- name: Install System Packages 1
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev"]

- name: Install System Packages 2
  become: true
  apt:
    name: ["lua5.1", "unzip", "libtool", "libtool-bin", "gettext"]

- name: Install System Packages 3
  become: true
  apt:
    name: ["htop", "curl", "wget", "tilix", "snapd", "fonts-firacode", "snapd", "flameshot", "ripgrep", "fzf"]


