- name: Install stow
  become: true
  apt:
    name: stow

- name: Clone dotfiles
  become: false
  ansible.builtin.git:
    repo: "https://github.com/marcioflaviof/.dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"

- name: Remove zshrc
  become: true
  file:
    state: absent
    path: "{{ lookup('env', 'HOME') }}/.zshrc"

- name: Remove bashrc
  become: true
  file:
    state: absent
    path: "{{ lookup('env', 'HOME') }}/.bashrc"

- name: Stow!
  become: false
  shell: "cd {{ lookup('env', 'HOME') }}/.dotfiles && stow ."
