- name: Install asdf dependencies
  become: true
  apt:
    name: ["unzip", "git", "autoconf", "automake", "gcc",
  "g++", "make", "patch", "pkg-config", "binutils", "libtool", "bison", "libreadline-dev"]

- name: Install node dependencies
  become: true
  apt:
    name: ["gpg", "dirmngr"]

- name: Install ruby dependencies
  become: true
  apt:
    name: ["libssl-dev", "libyaml-dev", "zlib1g-dev", "libncurses5-dev", "libffi-dev"]

- name: Install asdf
  become: false
  ansible.builtin.git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: "{{ lookup('env', 'HOME') }}/.asdf"
    version: "{{ asdf_version }}"

- name: "source asdf script"
  template:
    src: "asdf.sh.j2"
    dest: "/etc/profile.d/asdf.sh"
    owner: "root"
    group: "root"
    mode: 0755
  become: True

- include_tasks: nodejs.yml

- include_tasks: ruby.yml
