- name: check if ruby plugin is installed
  become: false
  shell: "bash -lc 'asdf list | grep ruby'"
  register: ruby_plugin_exists
  ignore_errors: true

- name: install ruby plugin for asdf
  become: false
  shell: "bash -lc 'asdf plugin-add ruby'"
  when: ruby_plugin_exists is not successful
      
- name: check installed ruby version
  become: false
  shell: "bash -lc 'asdf list ruby | grep {{ ruby_version }}'"
  register: ruby_version_exists
  ignore_errors: true

- name: install ruby
  become: false
  shell: "bash -lc 'asdf install ruby {{ ruby_version }}'"
  register: ruby_installed
  when: ruby_version_exists is not successful

- name: set global ruby version
  become: false
  shell: "bash -lc 'asdf global ruby {{ ruby_version }}'"
  when: ruby_version_exists is successful or ruby_installed is successful

- name: reshim ruby
  become: false
  shell: "bash -lc 'asdf reshim ruby'"
  when: ruby_version_exists is successful or ruby_installed is successful
