- name: Install Docker Dependencies
  become: true
  apt: name={{ item }} state=latest update_cache=yes
  loop:
    [
      "apt-transport-https",
      "ca-certificates",
      "curl",
      "software-properties-common",
      "python3-pip",
      "virtualenv",
      "python3-setuptools",
    ]

- name: Install aptitude using apt
  become: true
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

- name: Add Docker GPG apt Key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker-ce

- name: Update apt and install docker-ce
  become: true
  apt: update_cache=yes name=docker-ce state=latest

- name: Install Docker
  become: true
  apt:
    name: docker-ce

- name: Adding existing user to group Docker
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

- name: Install Docker-Compose
  become: true
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-Linux-x86_64"
    dest: "/usr/local/bin/docker-compose"
    mode: 755
